export const TELEMETRY_SCHEMA_VERSION = "1.2.0";

export enum EventCategory {
    UI = "ui",
    API = "api",
    ORCHESTRATOR = "orchestrator",
    PLANNER = "planner",
    VALIDATOR = "validator",
    MATERIALIZER = "materializer",
    STATE = "state",
    DRIFT = "drift",
    FILESYSTEM = "filesystem",
    RUNTIME = "runtime",
    DATABASE = "database",
    SECURITY = "security",
    MCP = "mcp",
    TRANSPORT = "transport",
    INTELLIGENCE = "intelligence",
    GOVERNANCE = "governance"
}

export enum ToolCategory {
    DISCOVERY = "DISCOVERY",
    VALIDATION = "VALIDATION",
    PLANNING = "PLANNING",
    EXECUTION = "EXECUTION",
    MUTATION = "MUTATION",
    GOVERNANCE = "GOVERNANCE",
    METRICS = "METRICS",
    MEMORY = "MEMORY"
}

export enum EventType {
    REQUEST_RECEIVED = "REQUEST_RECEIVED",
    SPEC_NORMALIZED = "SPEC_NORMALIZED",
    DRIFT_SCAN_STARTED = "DRIFT_SCAN_STARTED",
    DRIFT_SCAN_COMPLETED = "DRIFT_SCAN_COMPLETED",
    DRIFT_DETECTED = "DRIFT_DETECTED",
    RECONCILIATION_DECIDED = "RECONCILIATION_DECIDED",
    RULE_STARTED = "RULE_STARTED",
    RULE_COMPLETED = "RULE_COMPLETED",
    RULE_FAILED = "RULE_FAILED",
    VALIDATION_STARTED = "VALIDATION_STARTED",
    VALIDATION_COMPLETED = "VALIDATION_COMPLETED",
    VALIDATION_FAILED = "VALIDATION_FAILED",
    PLAN_GENERATED = "PLAN_GENERATED",
    PLAN_APPLIED = "PLAN_APPLIED",
    PLAN_REJECTED = "PLAN_REJECTED",
    PLAN_FAILED = "PLAN_FAILED",
    MATERIALIZATION_STARTED = "MATERIALIZATION_STARTED",
    MATERIALIZATION_COMPLETED = "MATERIALIZATION_COMPLETED",
    MATERIALIZATION_REJECTED = "MATERIALIZATION_REJECTED",
    MATERIALIZATION_FAILED = "MATERIALIZATION_FAILED",
    STATE_SAVED = "STATE_SAVED",
    VFS_COMMIT_STARTED = "VFS_COMMIT_STARTED",
    VFS_COMMIT_COMPLETED = "VFS_COMMIT_COMPLETED",
    EXECUTION_STARTED = "EXECUTION_STARTED",
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED",
    EXECUTION_FAILED = "EXECUTION_FAILED",
    ORCHESTRATION_STARTED = "ORCHESTRATION_STARTED",
    ORCHESTRATION_COMPLETED = "ORCHESTRATION_COMPLETED",
    ORCHESTRATION_FAILED = "ORCHESTRATION_FAILED",
    HTTP_REQUEST_STARTED = "HTTP_REQUEST_STARTED",
    HTTP_REQUEST_COMPLETED = "HTTP_REQUEST_COMPLETED",
    DB_QUERY = "DB_QUERY",
    HEALTHCHECK_RESULT = "HEALTHCHECK_RESULT",
    MCP_TOOL_STARTED = "MCP_TOOL_STARTED",
    MCP_TOOL_COMPLETED = "MCP_TOOL_COMPLETED",
    MCP_TOOL_FAILED = "MCP_TOOL_FAILED",
    REMOTE_REQUEST_STARTED = "REMOTE_REQUEST_STARTED",
    MCP_ROUTE_SELECTED = "MCP_ROUTE_SELECTED",
    MCP_WORKER_ASSIGNED = "MCP_WORKER_ASSIGNED",
    MCP_WORKER_RELEASED = "MCP_WORKER_RELEASED",
    MCP_WORKER_COMPLETED = "MCP_WORKER_COMPLETED",
    IMMUNE_SYSTEM_TRIGGERED = "IMMUNE_SYSTEM_TRIGGERED",
    HEARTBEAT_DOC_REFRESH_STARTED = "HEARTBEAT_DOC_REFRESH_STARTED",
    DECISION_LOG_WRITTEN = "DECISION_LOG_WRITTEN",
    SESSION_CONNECTED = "SESSION_CONNECTED",
    AUTH_RESOLVED = "AUTH_RESOLVED",
    OUTCOME_EVALUATED = "OUTCOME_EVALUATED",
    OUTCOME_SUCCESS = "OUTCOME_SUCCESS",
    OUTCOME_FAILED = "OUTCOME_FAILED",
    SUGGESTION_GENERATED = "SUGGESTION_GENERATED",
    POLICY_ALLOWED = "POLICY_ALLOWED",
    POLICY_DENIED = "POLICY_DENIED",
    WORKFLOW_STATE_TRANSITION = "WORKFLOW_STATE_TRANSITION",
    CIRCUIT_OPENED = "CIRCUIT_OPENED",
    CIRCUIT_HALF_OPEN = "CIRCUIT_HALF_OPEN",
    CIRCUIT_CLOSED = "CIRCUIT_CLOSED",
    FALLBACK_SELECTED = "FALLBACK_SELECTED",
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
}

export enum Severity {
    INFO = "INFO",
    WARN = "WARN",
    ERROR = "ERROR",
    FATAL = "FATAL"
}

export enum Component {
    CLI = "cli",
    ORCHESTRATOR = "orchestrator",
    MATERIALIZER = "materializer",
    VFS = "vfs",
    STATE_MANAGER = "state_manager",
    RUNTIME_API = "runtime_api"
}
